# This is an example conf file for argos backend
# Copy it, rename it "config.yaml" and fill in the values to use it

name: "Argos Back"  # Name of the API
debug: false         # If true, flask will be launched in debug mode
port: 8722          # Port for the Flask API
logging_level: "warning"  # Python / flask logging level
upload:
  folder: "./uploads"            # Local folder in which the uploaded pictures are saved
                                 # "./uploads" is the recommended value (already in .gitignore)
  extensions: ["jpg", "jpeg",]   # File extensions accepted by the API
processed_pictures_path: "./data/processed"